package contextwindow

import (
	"context"
	"fmt"
	"strings"
	"sync"
	"sync/atomic"
	"time"

	"github.com/jerryschen31/minimal-agent/config"
	"github.com/jerryschen31/minimal-agent/model"
)

const WindowStrategy = "offset" // default context window strategy: "offset", "in-place", "ring-buffer", "linked-list"
const SummarizeSystemPrompt = "You are a helpful assistant that summarizes chat history. Summarize the key conversational points and important details concisely."
const MaxContextWindow = 10          // maximum number of messages to keep in the sliding context window
const AutoCompactThresholdFrac = 0.9 // fraction threshold of the context window at which automatic compaction is triggered

// Context for a chat session
type ChatContext struct {
	mu                   sync.Mutex
	window               ContextWindow // The context window is the data structure that holds the actual chat messages
	gen                  int           // Generation counter - increments each time the context is compacted or cleared
	autoCompactThreshold int
	compactInProgress    atomic.Bool
	CompactWG            sync.WaitGroup // Used for triggering some code that waits for compaction to complete (e.g., for graceful shutdown)
}

// This is a snapshot of the context window's state, including the current chat history and the generation counter.
type ContextState struct {
	Messages []model.ChatMessage
	Gen      int
}

func NewChatContext(w ContextWindow, autoCompactThreshold int) (*ChatContext, error) {
	return &ChatContext{
		window:               w,
		gen:                  0,
		autoCompactThreshold: autoCompactThreshold,
		compactInProgress:    atomic.Bool{},
	}, nil
}

func (c *ChatContext) GetWindow() ContextWindow {
	return c.window
}

func (c *ChatContext) ShouldStartCompaction() bool {
	return c.compactInProgress.CompareAndSwap(false, true)
}

func (c *ChatContext) EndCompaction() {
	c.compactInProgress.Store(false)
}

func (c *ChatContext) IsAutoCompactionNeeded() bool {
	return c.window.GetSize() >= c.autoCompactThreshold
}

// WaitForCompaction blocks until any in-flight background compaction finishes. Safe to call
// even when none is running — Wait() on a zero counter returns immediately, no blocking.
// This is useful for code that needs to ensure all background compaction has completed before proceeding, such as during graceful shutdown.
func (c *ChatContext) WaitForCompaction() {
	c.CompactWG.Wait()
}

func (c *ChatContext) AddMessages(msgs []model.ChatMessage) {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.window.AddMessages(msgs)
}

func (c *ChatContext) GetMessages() []model.ChatMessage {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.window.GetMessages()
}

func (c *ChatContext) RemoveLast(n int) {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.window.RemoveLast(n)
}

func (c *ChatContext) GetSize() int {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.window.GetSize()
}

func (c *ChatContext) GetMaxSize() int {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.window.GetMaxSize()
}

// Snapshot() gets a snapshot of the state for the current context window - for now this includes the chat history and the generation counter
func (c *ChatContext) Snapshot() ContextState {
	c.mu.Lock()
	defer c.mu.Unlock()
	return ContextState{
		Messages: c.window.GetMessages(),
		Gen:      c.gen,
	}
}

func (c *ChatContext) Clear() {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.window.Clear()
	c.gen++
}

func (c *ChatContext) Compact(state ContextState, summaryMsg model.ChatMessage) bool {
	c.mu.Lock()
	defer c.mu.Unlock()

	if c.gen != state.Gen {
		// if the context window has been cleared or compacted since the snapshot was taken, compaction cannot be safely performed
		return false
	}

	// get the IDs for the messages that are being compacted as a hash set (in case new messages are added concurrently while the summary is being generated by the LLM)
	stateMessageIDs := getMessageIDs(state.Messages)

	// create a new message slice, replacing the snapshot messages that were summarized with the summary message, and then any new messages that were inserted since the compaction started (preserving their order).
	newMessages := append([]model.ChatMessage(nil), summaryMsg)
	for _, msg := range c.window.GetMessages() {
		if !stateMessageIDs[msg.ID] {
			newMessages = append(newMessages, msg)
		}
	}
	// there is an edge case where maxSize new messages are added concurrently before compaction finishes, so we may need to trim the message slice to fit within the maximum size.
	newMessages = clampToMax(newMessages, c.window.GetMaxSize())

	// replace the messages in the context window with the new messages
	c.window.Clear()
	c.window.AddMessages(newMessages)
	c.gen++

	return true
}

// given a slice of chat messages,get message IDs back as a map
// this assumes that ID is unique and present for each message
func getMessageIDs(messages []model.ChatMessage) map[string]bool {

	messageIDs := make(map[string]bool, len(messages))
	for _, m := range messages {
		if m.ID == "" {
			continue
		}
		messageIDs[m.ID] = true
	}
	return messageIDs
}

// clampToMax trims a compacted message slice (summary at [0], then surviving messages oldest-to-newest) to at most maxSize messages.
// This only matters in the rare event that enough new messages were added while the summary was being generated that the summary
// plus every survivor no longer fits. The summary is always kept and the oldest survivors are dropped first.
// It assumes maxSize >= 1 and returns msgs unchanged (not copied) when it already fits.
func clampToMax(msgs []model.ChatMessage, maxSize int) []model.ChatMessage {
	if len(msgs) <= maxSize {
		return msgs
	}
	// skip orphaned tool messages at the beginning (these are tool messages where the initial user / assistant messages were cut off because they fell outside the context)
	start := len(msgs) - (maxSize - 1)
	for start < len(msgs) && msgs[start].Role == "tool" {
		start++
	}
	// allocate a fresh slice so we don't alias msgs' backing array
	trimmed := make([]model.ChatMessage, 0, maxSize)
	trimmed = append(trimmed, msgs[0])
	return append(trimmed, msgs[start:]...)
}

// creates a new chat context instance
func SetupChatContext(cfg config.Config) (*ChatContext, error) {
	// create context window data structure
	w, err := NewContextWindow(MaxContextWindow, WindowStrategy)
	if err != nil {
		return nil, err
	}

	// create chat context using context window
	threshold := int(float64(w.GetMaxSize()) * AutoCompactThresholdFrac)
	cc, err := NewChatContext(w, threshold)
	if err != nil {
		return nil, err
	}
	return cc, nil
}

// makes a call to the provider to summarize the given chat messages
func SummarizeChatContext(ctx context.Context, p model.Provider, msgs []model.ChatMessage, addlInstructions string) (string, error) {
	if len(msgs) == 0 {
		return "", fmt.Errorf("no messages to summarize")
	}
	// render the messages as plain text, one block per message
	var transcript strings.Builder
	for _, m := range msgs {
		fmt.Fprintf(&transcript, "%s: %s\n", m.Role, m.Content)
		for _, call := range m.ToolCalls {
			fmt.Fprintf(&transcript, "tool_call %s: %s(%s)\n", call.ID, call.Function.Name, call.Function.Arguments)
		}
		if m.ToolCallID != "" {
			fmt.Fprintf(&transcript, "tool_call_id: %s\n", m.ToolCallID)
		}
	}

	// Create a brand-new model.ChatMessages slice, so we never touch the original backing array.
	req := []model.ChatMessage{
		{Role: "system", Content: SummarizeSystemPrompt},
		{Role: "user", Content: "<transcript>\n" + transcript.String() + "</transcript>"},
	}
	if addlInstructions != "" {
		req = append(req, model.ChatMessage{Role: "system", Content: addlInstructions})
	}

	resp, err := p.Chat(ctx, req, nil)
	if err != nil {
		return "", fmt.Errorf("summarize: %w", err)
	}

	// Chat response summary could be nil, which should be considered an error.
	summary := strings.TrimSpace(resp.Content)
	if summary == "" {
		return "", fmt.Errorf("summarize: model returned an empty summary")
	}
	return summary, nil
}

// compacts the chat context by summarizing the current messages and replacing them with a single system message containing the summary.
// in the future, the compaction could be more sophisticated (compacting a subset of messages, merging similar messages, having categories for messages, etc.)
// compactionType values for compactChatContext, distinguishing a manual /compact from an
// auto-triggered one (only affects the "triggered..." message printed to the user).

// addlInstructions provide additional information for the summarization process, guiding how the chat context should be summarized.
func CompactChatContext(ctx context.Context, chatctx *ChatContext, p model.Provider, addlInstructions string) (model.ChatMessage, error) {
	defer chatctx.EndCompaction() // ensure the compaction lock is released after compaction is done

	// take a snapshot of the current chat history
	state := chatctx.Snapshot()

	// summarize the chat history
	summary, err := SummarizeChatContext(ctx, p, state.Messages, addlInstructions)
	if err != nil {
		return model.ChatMessage{}, err
	}

	// create a new message history, removing all of the messages that were in the snapshot that was summarized
	summaryMsg := model.ChatMessage{
		Role:      "user",
		Content:   summary,
		Timestamp: time.Now().UTC(), // .Format(time.RFC3339),
		ID:        model.CreateID(), // uuid.New().String(),
		Type:      "summary",
	}
	isCompacted := chatctx.Compact(state, summaryMsg)
	if isCompacted {
		// optionally, you could log or perform some action when compaction succeeds
		return summaryMsg, nil
	} else {
		return model.ChatMessage{}, fmt.Errorf("[system] Chat context compaction failed")
	}
}

// print the current chat context, just for debugging purposes - prints to the standard output (console)
func DebugChatContext(msgContext []model.ChatMessage) {
	fmt.Println("[debug] --- context window ---")
	for i, msg := range msgContext {
		fmt.Printf("[%d] %s: %s\n", i, msg.Role, msg.Content)
	}
	fmt.Println("[debug] --- end ---")
}
